package com.ap.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public enum CropsType {
    BlueJazz("BlueJazz",
            new ArrayList<>(Arrays.asList(1, 2, 2, 2)),
            7,
            true,
             null,
            50,
            45,
            new ArrayList<>(List.of( Season.Spring)),
            false ),
    Carrot("Carrot",
            new ArrayList<>(Arrays.asList(1, 1, 1)),
            3,
            true,
             null,
            35,
            75,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Cauliflower("Cauliflower",
            new ArrayList<>(Arrays.asList(1, 2, 4, 4, 1)),
            12,
            true,
             null,
            175,
            75,
            new ArrayList<>(List.of( Season.Spring)),
            true ),
    Coffee("CoffeeBean",
            new ArrayList<>(Arrays.asList(1, 2, 2, 3, 2)),
            10,
            false,
            2,
            15,
            null,
            new ArrayList<>(List.of( Season.Spring,  Season.Summer)),
            false),
    Garlic("Garlic",
            new ArrayList<>(Arrays.asList(1, 1, 1, 1)),
            4,
            true,
             null,
            60,
            20,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Kale("Kale",
            new ArrayList<>(Arrays.asList(1, 2, 2, 1)),
            6,
            true,
             null,
            110,
            50,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Parsnip("Parsnip",
            new ArrayList<>(Arrays.asList(1, 1, 1, 1)),
            4,
            true,
             null,
            35,
           25,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Potato("Potato",
            new ArrayList<>(Arrays.asList(1, 1, 1, 2, 1)),
            6,
            true,
             null,
            80,
            25,
            new ArrayList<>(List.of( Season.Spring)),
            false),

    Rhubarb("Rhubarb",
            new ArrayList<>(Arrays.asList(2, 2, 2, 3, 4)),
            13,
            true,
             null,
            220,
            null,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Strawberry("Strawberry",
            new ArrayList<>(Arrays.asList(1, 1, 2, 2, 2)),
            8,
            false,
            4,
            120,
            50,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Tulip("Tulip",
            new ArrayList<>(Arrays.asList(1, 1, 2, 2)),
            6,
            true,
             null,
            30,
            45,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Unmilled_Rice("UnmilledRice",
            new ArrayList<>(Arrays.asList(1, 2, 2, 3)),
            8,
            true,
             null,
            30,
            3,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Blueberry("Blueberry",
            new ArrayList<>(Arrays.asList(1, 3, 3, 4, 2)),
            13,
            false,
            4,
            50,
            25,
            new ArrayList<>(List.of( Season.Spring)),
            false),
    Corn("Corn",
            new ArrayList<>(Arrays.asList(2, 3, 3, 3, 3)),
            14,
            false,
            4,
            50,
            25,
            new ArrayList<>(List.of( Season.Summer,  Season.Fall)),
            false),
    Hot_Pepper("HotPepper",
            new ArrayList<>(Arrays.asList(1, 1, 1, 3, 1)),
            5,
            false,
            3,
            40,
            13,
            new ArrayList<>(List.of( Season.Summer)),
            false),
    Melon("Melon",
            new ArrayList<>(Arrays.asList(1, 2, 3, 3, 3)),
            12,
            true,
             null,
            250,
            113,
            new ArrayList<>(List.of( Season.Summer)),
            true),
    Poppy("Poppy",
            new ArrayList<>(Arrays.asList(1, 2, 2, 2)),
            7,
            true,
             null,
            140,
            45,
            new ArrayList<>(List.of( Season.Summer)),
            false),
    Radish("Radish",
            new ArrayList<>(Arrays.asList(2, 1, 2, 1)),
            6,
            true,
             null,
            90,
            45,
            new ArrayList<>(List.of( Season.Summer)),
            false),
    Red_Cabbage("RedCabbage",
            new ArrayList<>(Arrays.asList(2, 1, 2, 2, 2)),
            9,
            true,
             null,
            260,
            75,
            new ArrayList<>(List.of( Season.Summer)),
            false ),
    StarFruit("Starfruit",
            new ArrayList<>(Arrays.asList(1, 2, 3, 3, 4)),
            13,
            true,
             null,
            750,
           125,
            new ArrayList<>(List.of( Season.Summer)),
            false),
    Summer_Spangle("SummerSpangle",
            new ArrayList<>(Arrays.asList(1, 2, 3, 1)),
            8,
            true,
             null,
            90,
            45,
            new ArrayList<>(List.of( Season.Summer)),
            false),
    Summer_Squash("SummerSquash",
            new ArrayList<>(Arrays.asList(1, 1, 1, 2, 1)),
            6,
            false,
            3,
            45,
            63,
            new ArrayList<>(List.of( Season.Summer)),
            false),
    Sunflower("Sunflower",
            new ArrayList<>(Arrays.asList(1, 2, 3, 2)),
            8,
            true,
             null,
            80,
            45,
            new ArrayList<>(List.of( Season.Summer,  Season.Fall)),
            false),
    Tomato("Tomato",
            new ArrayList<>(Arrays.asList(2, 2, 2, 2, 3)),
            11,
            false,
            4,
            60,
            20,
            new ArrayList<>(List.of( Season.Summer)),
            false),
    Wheat("Wheat",
            new ArrayList<>(Arrays.asList(1, 1, 1, 1)),
            4,
            true,
             null,
            25,
            null,
            new ArrayList<>(List.of( Season.Summer,  Season.Fall)),
            false),
    Amaranth("Amaranth",
            new ArrayList<>(Arrays.asList(1, 2, 2, 2)),
            7,
            true,
             null,
            150,
            50,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Artichoke("Artichoke",
            new ArrayList<>(Arrays.asList(2, 2, 1, 2, 1)),
            8,
            true,
             null,
            160,
            30,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Beet("Beet",
            new ArrayList<>(Arrays.asList(1, 1, 2, 2)),
            6,
            true,
             null,
            100,
            30,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Bok_Choy("BokChoy",
            new ArrayList<>(Arrays.asList(1, 1, 1, 1)),
            4,
            true,
             null,
            80,
            25,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Broccoli("Broccoli",
            new ArrayList<>(Arrays.asList(2, 2, 2, 2)),
            8,
            false,
            4,
            70,
            63,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Eggplant("Eggplant",
            new ArrayList<>(Arrays.asList(1, 1, 1, 1)),
            5,
            false,
            5,
            60,
            20,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Fairy_Rose("FairyRose",
            new ArrayList<>(Arrays.asList(1, 4, 4, 3)),
            12,
            true,
             null,
            290,
            45,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Grape("Grape",
            new ArrayList<>(Arrays.asList(1, 1, 2, 3, 3)),
            10,
            false,
            3,
            80,
            38,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Pumpkin("Pumpkin",
            new ArrayList<>(Arrays.asList(1, 2, 3, 4, 3)),
            13,
            true,
             null,
            320,
            null,
            new ArrayList<>(List.of( Season.Fall)),
            true),
    Yam("Yam",
            new ArrayList<>(Arrays.asList(1, 3, 3, 3)),
            10,
            true,
             null,
            160,
            45,
            new ArrayList<>(List.of( Season.Fall)),
            false),
    Powdermelon("Powdermelon",
            new ArrayList<>(Arrays.asList(1, 2, 1, 2, 1)),
            7,
            true,
             null,
            60,
            63,
            new ArrayList<>(List.of( Season.Fall)),
            true),
    AncientFruit("AncientFruit",
            new ArrayList<>(Arrays.asList(2, 7, 7, 7, 5)),
            28,
            false,
            7,
            550,
            null,
            new ArrayList<>(List.of( Season.Spring,  Season.Summer,  Season.Fall)),
            false);
    
    private final String name;
    private final ArrayList<Integer> stage;
    private final int harvestTime;
    private final boolean oneTime;
    private final Integer regrowthTime;
    private final int baseSellPrice;
    // Null if it's not eatable
    private final Integer energyProduce;
    private final ArrayList< Season>  SeasonList;
    private final boolean canBecomeGiant;

    CropsType(String name,
               ArrayList<Integer> stage,
               int harvestTime,
               boolean oneTime,
               Integer regrowthTime,
               int baseSellPrice,
               Integer energyProduce,
               ArrayList< Season>  SeasonList,
               boolean canBecomeGiant
    ) {
        this.name = name;
        this.harvestTime = harvestTime;
        this.oneTime = oneTime;
        this.regrowthTime = regrowthTime;
        this.baseSellPrice = baseSellPrice;
        this.energyProduce = energyProduce;
        this.SeasonList = SeasonList;
        this.canBecomeGiant = canBecomeGiant;
        this.stage = stage;
    }

    public String getName() {
        return name;
    }

    public ArrayList<Integer> getStage() {
        return stage;
    }

    public int getHarvestTime() {
        return harvestTime;
    }

    public boolean isOneTime() {
        return oneTime;
    }

    public Integer getRegrowthTime() {
        return regrowthTime;
    }

    public int getBaseSellPrice() {
        return baseSellPrice;
    }

    public Integer getEnergyProduce() {
        return energyProduce;
    }

    public ArrayList<Season> getSeasonList() {
        return SeasonList;
    }

    public boolean isCanBecomeGiant() {
        return canBecomeGiant;
    }
    
}
